User previously accepted permissions
Bespin-AF/a2d2-android pull request #1
Opened 2018-11-20 19:43 UTC by greenpaw94

Finished the story point.   LINK: https://www.pivotaltracker.com/story/show/161752748

Added comments and renamed some files to begin uniform naming conventions.

2018-11-20 20:00 UTC, Medlinator commented on app/src/androidTest/java/com/example/bespinaf/a2d2/test_denies_permissions.java
> +    @Test //Tests the user can see an error pop-up when they deny permissions
Update comment to reflect standard practice. Example:

/**
 * Lorem ipsum
 *
 * @param derp
 */
public void String canUserAgree(String derp) {
}

2018-11-20 20:23 UTC, Medlinator requested changes
Updates comments to reflect standard practice. 

Suggestion: Implement Butterknife.

2018-11-21 15:12 UTC, Daesthelos commented
Amended styling and comments
Failed to integrate Butterknife: receiving dexcompilation error

2018-11-21 15:55 UTC, merged

2018-11-21 16:54 UTC, Medlinator commented
Change toast to a snackbar.